package ai

type AISummarizer interface {
	GenerateSummary(text string, prompt string) (string, error)
}

// PlaceholderAISummarizer is a concrete implementation of AISummarizer that returns a predefined summary.
type PlaceholderAISummarizer struct{
	Err error
	BinaryName string
}

func (p *PlaceholderAISummarizer) GenerateSummary(text string, prompt string) (string, error) {
	if p.Err != nil {
		return "", p.Err
	}
	// In a real scenario, this would call an AI model using p.BinaryName.
	// For now, it returns a simple placeholder summary.
	return "This is a placeholder summary generated by the AI agent.", nil
}

// NewAISummarizer creates a new AISummarizer based on the provided binary name.
func NewAISummarizer(binaryName string) AISummarizer {
	// In a real application, this would return different implementations
	// based on the binaryName (e.g., a GeminiAISummarizer, a ClaudeAISummarizer).
	// For now, we return a PlaceholderAISummarizer.
	return &PlaceholderAISummarizer{BinaryName: binaryName}
}

// MockAISummarizer is a mock implementation of the AISummarizer interface for testing.
type MockAISummarizer struct {
	Summary string
	Err     error
}

func (m *MockAISummarizer) GenerateSummary(text string, prompt string) (string, error) {
	return m.Summary, m.Err
}